rootPageId: 1
base: /
baseVariants: {  }
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: gb
  -
    title: german
    enabled: true
    languageId: '1'
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: de
  -
    title: japanese
    enabled: true
    languageId: '2'
    base: /ja/
    typo3Language: default
    locale: ja_JA.UTF-8
    iso-639-1: ja
    navigationTitle: Japanese
    hreflang: ja-JA
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: jp
errorHandling: {  }
routes: {  }
